package main

const VARNAM_MATCH_EXACT = 1
const VARNAM_MATCH_POSSIBILITY = 2

const VARNAM_TOKEN_CHAR = 1
const VARNAM_TOKEN_SYMBOL = 2

const VARNAM_TOKEN_BASIC_WEIGHT = 10

const VARNAM_SYMBOL_VOWEL = 1
const VARNAM_SYMBOL_CONSONANT = 2
const VARNAM_SYMBOL_DEAD_CONSONANT = 3
const VARNAM_SYMBOL_CONSONANT_VOWEL = 4
const VARNAM_SYMBOL_NUMBER = 5
const VARNAM_SYMBOL_SYMBOL = 6
const VARNAM_SYMBOL_ANUSVARA = 7
const VARNAM_SYMBOL_VISARGA = 8
const VARNAM_SYMBOL_VIRAMA = 9
const VARNAM_SYMBOL_OTHER = 10
const VARNAM_SYMBOL_NON_JOINER = 11
const VARNAM_SYMBOL_JOINER = 12
const VARNAM_SYMBOL_PERIOD = 13

// VARNAM_PATTERN_WORD_MIN_CONFIDENCE Minimum confidence for words in patterns dictionary. These words are mostly english and won't work with malayalam transliteration
const VARNAM_PATTERN_WORD_MIN_CONFIDENCE = 30
